name: Test Build

on:
    push:
        branches:
            - main

jobs:
    test-build:
        name: "Test Build"
        runs-on: ubuntu-latest
        container:
            image: python:3.8

        steps:
            - name: Check out repository code
              uses: actions/checkout@v2
              with:
                  submodules: recursive
            - name: Install build dependencies
              run: pip install build virtualenv
            - name: Test build
              run: python -m build
            - name: Verify files in build
              run: |
                for f in generativeimage2text/* generativeimage2text/**/*;
                do
                    tar -tzvf dist/generativeimage2text-0.1.tar.gz | grep -q $f
                    if [ $? -eq 1 ]; then
                        exit 1
                    fi
                done
